baseURL = "https://anugrahra.space/"
languageCode = "en-us"
title = "â–² anugrahra.space â–²"
theme = "anugrahtheme"
rssLimit = 20
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[author]
	name = "Anugrah Ramadhan"
	email = ""

[permalinks]
  posts = "/catatan/:title/"

[taxonomies]
  tagline = 'tagline'
  category = 'categories'
  tag = 'tags'

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Dukung"
    url = "https://saweria.co/AnugrahRamadhan"
    weight = 2
  [[menu.main]]
    name = "Kontak"
    url = "/kontak/"
    weight = 3
  [[menu.main]]
    name = "RSS"
    url = "/catatan/index.xml"
    weight = 4

  [[menu.landing]]
    name = "ğŸ“ Words"
    url = "/catatan/"
    weight = 1
  [[menu.landing]]
    name = "ğŸ“š Zines"
    url = "/seri-tulisan/"
    weight = 2
  [[menu.landing]]
    name = "ğŸ¤– Codes"
    url = "/karya-koding/"
    weight = 3
  [[menu.landing]]
    name = "ğŸ¨ Artssshole"
    url = "/artwork/"
    weight = 4
  [[menu.landing]]
    name = "ğŸ™ï¸ Podcast"
    url = "https://anchor.fm/dekadensiotak"
    weight = 5
  [[menu.landing]]
    name = "â–¶ï¸ Youtube"
    url = "https://www.youtube.com/channel/UCdZ7OvSMv2ygAplHpHR_yLQ"
    weight = 6
