baseURL = "https://anugrahra.space/"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
languageCode = "en-us"
rssLimit = 20
theme = "anugrahtheme"
title = "â–² anugrahra.space â–²"
googleAnalytics = "UA-227767430-1"

[author]
email = ""
name = "Anugrah Ramadhan"
[markup.goldmark.renderer]
unsafe = true

[[menu.landing]]
name = "ğŸ¨ Artwork"
url = "/artwork/"
weight = 4
[[menu.landing]]
name = "ğŸ“š Seri Tulisan"
url = "/seri-tulisan/"
weight = 2
[[menu.landing]]
name = "ğŸ“ Catatan"
url = "/catatan/"
weight = 1
[[menu.landing]]
name = "â–¶ï¸ Youtube"
url = "https://www.youtube.com/channel/UCdZ7OvSMv2ygAplHpHR_yLQ"
weight = 6
[[menu.landing]]
name = "ğŸ™ï¸ Podcast"
url = "https://anchor.fm/dekadensiotak"
weight = 5
[[menu.landing]]
name = "ğŸ¤– Codes"
url = "/karya-koding/"
weight = 3

[[menu.main]]
name = "RSS"
url = "/catatan/index.xml"
weight = 4
[[menu.main]]
name = "Kontak"
url = "/kontak/"
weight = 3
[[menu.main]]
name = "Dukung"
url = "https://saweria.co/AnugrahRamadhan"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.tulisan]]
name = "How to be a stoic"
url = "/catatan/how-to-be-a-stoic/"
weight = 5
[[menu.tulisan]]
name = "Kamu gak spesial"
url = "/catatan/kamu-gak-spesial/"
weight = 4
[[menu.tulisan]]
name = "Edukasi Internet"
url = "/catatan/edukasi-internet/"
weight = 3
[[menu.tulisan]]
name = "Bermain di internet"
url = "/catatan/bermain-di-internet/"
weight = 2
[[menu.tulisan]]
name = "Semua orang bermasalah"
url = "/catatan/semua-orang-bermasalah/"
weight = 1

[permalinks]
posts = "/catatan/:title/"
[taxonomies]
category = "categories"
tag = "tags"
tagline = "tagline"
