baseURL = "https://anugrahra.space/"
languageCode = "en-us"
title = "Anugrah Ramadhan's Digital Museum ğŸº"
theme = "anugrahtheme"

[permalinks]
  posts = "/catatan/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Anjing"
    pre = "alert-triangle"
    url = "/tags/"
    weight = 4

  [[menu.landing]]
    name = "ğŸ“ Catatan"
    url = "/catatan/"
    weight = 1
  [[menu.landing]]
    name = "ğŸ“š Seri Tulisan"
    url = "/seri-tulisan/"
    weight = 2
  [[menu.landing]]
    name = "ğŸ¤– Karya Koding"
    url = "/karya-koding/"
    weight = 3
  [[menu.landing]]
    name = "ğŸ¨ Artwork"
    url = "/artwork/"
    weight = 4
  [[menu.landing]]
    name = "ğŸ™ï¸ Podcast"
    url = "/podcast/"
    weight = 5