baseURL = "https://anugrahra.space/"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
languageCode = "en-us"
rssLimit = 20
theme = "anugrahtheme"
title = "â–² anugrahra.space â–²"
description = "Website Anugrah Ramadhan"
googleAnalytics = "UA-227767430-1"

[author]
email = "anugrahra.space@gmail.com"
name = "Anugrah Ramadhan"
[markup.goldmark.renderer]
unsafe = true

[[menu.landing]]
name = "ğŸ“ Catatan"
url = "/catatan/"
weight = 1
[[menu.landing]]
name = "ğŸ“š Seri Tulisan"
url = "/seri-tulisan/"
weight = 2
[[menu.landing]]
name = "ğŸ¤– Codes"
url = "/karya-koding/"
weight = 3

[[menu.main]]
name = "RSS"
url = "/catatan/index.xml"
weight = 4
[[menu.main]]
name = "Kontak"
url = "/kontak/"
weight = 3
[[menu.main]]
name = "Dukung"
url = "https://saweria.co/AnugrahRamadhan"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.tulisan]]
name = "Belajar memilih dengan seni"
url = "/catatan/belajar-memilih-dengan-seni/"
weight = 5
img = "/icon/favicon.ico"
[[menu.tulisan]]
name = "Kamu gak spesial"
url = "/catatan/kamu-gak-spesial/"
weight = 4
[[menu.tulisan]]
name = "Ubah yang bisa diukur"
url = "/catatan/ubah-yang-bisa-diukur/"
weight = 3
[[menu.tulisan]]
name = "Bermain di internet"
url = "/catatan/bermain-di-internet/"
weight = 2
[[menu.tulisan]]
name = "Semua orang bermasalah"
url = "/catatan/semua-orang-bermasalah/"
weight = 1

[permalinks]
posts = "/catatan/:title/"
[taxonomies]
category = "categories"
tag = "tags"
tagline = "tagline"
image = "image"