baseURL     = "https://heyanugrah.com/"
title       = "hey anugrah!"
description = "anugrah's digital garden"
languageCode = "id-ID"
rssLimit    = 20
theme       = "anugrahtheme"

copyright  = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."

[author]
  name  = "Anugrah Ramadhan"
  email = "dialog.anugrah@gmail.com"

[markup.goldmark.renderer]
  unsafe = true

# ===========================
# MENUS
# ===========================
[[menu.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Dukung"
  url    = "https://saweria.co/AnugrahRamadhan"
  weight = 2

[[menu.main]]
  name   = "Kontak"
  url    = "/kontak/"
  weight = 3

[[menu.main]]
  name   = "RSS"
  url    = "/catatan/index.xml"
  weight = 5

# ===========================
# URL & TAXONOMIES
# ===========================
[permalinks]
  posts = "/catatan/:title/"

[taxonomies]
  category = "categories"
  tag      = "tags"
  tagline  = "tagline"
  image    = "image"

# ===============
# MENU LANDING
# ===============
[menu]

  [[menu.landing]]
    name = "üìÑ Baca Catatan Terbaru"
    url = "/catatan/temukita"
    weight = 1

  [[menu.landing]]
    name = "üìù Lihat Semua Catatan"
    url = "/catatan/"
    weight = 2

# ===============
# MENU TULISAN FOR YOU
# ===============

  [[menu.tulisan]]
  name = "Setelah Membaca Setelah Boombox"
  url = "/catatan/setelah-membaca-setelah-boombox/"
  weight = 1

  [[menu.tulisan]]
  name = "Bengkel Siasat"
  url = "/catatan/bengkel-siasat/"
  weight = 2

  [[menu.tulisan]]
  name = "Olahraga"
  url = "/catatan/olahraga/"


# ===============
# MENU RESENSI
# ===============

  [[menu.review]]
  name = "Anjing lah"
  url = "/catatan/das-kapital/"
  weight = 1