baseURL = "https://anugrahra.space/"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
languageCode = "en-us"
rssLimit = 20
theme = "anugrahtheme"
title = "â–² anugrahra.space â–²"
[author]
email = ""
name = "Anugrah Ramadhan"
[markup.goldmark.renderer]
unsafe = true
[[menu.landing]]
name = "ğŸ¨ Artwork"
url = "/artwork/"
weight = 4
[[menu.landing]]
name = "ğŸ“š Seri Tulisan"
url = "/seri-tulisan/"
weight = 2
[[menu.landing]]
name = "ğŸ“ Catatan"
url = "/catatan/"
weight = 1
[[menu.landing]]
name = "â–¶ï¸ Youtube"
url = "https://www.youtube.com/channel/UCdZ7OvSMv2ygAplHpHR_yLQ"
weight = 6
[[menu.landing]]
name = "ğŸ™ï¸ Podcast"
url = "https://anchor.fm/dekadensiotak"
weight = 5
[[menu.landing]]
name = "ğŸ¤– Codes"
url = "/karya-koding/"
weight = 3
[[menu.main]]
name = "RSS"
url = "/catatan/index.xml"
weight = 4
[[menu.main]]
name = "Kontak"
url = "/kontak/"
weight = 3
[[menu.main]]
name = "Dukung"
url = "https://saweria.co/AnugrahRamadhan"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[permalinks]
posts = "/catatan/:title/"
[taxonomies]
category = "categories"
tag = "tags"
tagline = "tagline"
