baseURL = "https://anugrahsite.netlify.app/"
languageCode = "en-us"
title = "Anugrah Ramadhan's Digital Museum"
theme = "anugrahtheme"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Anjing"
    pre = "alert-triangle"
    url = "/tags/"
    weight = 4

  [[menu.landing]]
    name = "ğŸ“ Catatan Pribadi"
    url = "/catatan/"
    weight = 1
  [[menu.landing]]
    name = "ğŸ“š Seri Tulisan"
    url = "/seri-tulisan/"
    weight = 2
  [[menu.landing]]
    name = "ğŸ¤– Beberapa program sederhana yang saya koding"
    url = "https://github.com/anugrahra"
    weight = 3
  [[menu.landing]]
    name = "âœ‚ï¸ Seni Kolase"
    url = "https://photos.app.goo.gl/5GWyngEEBNSvhRCD9"
    weight = 4
  [[menu.landing]]
    name = "ğŸ¨ Lukisan"
    url = ""
    weight = 5
  [[menu.landing]]
    name = "ğŸ™ï¸ Podcast"
    url = "https://anchor.fm/dekadensiotak"
    weight = 6
