baseURL     = "https://heyanugrah.com/"
title       = "hey anugrah!"
description = "Website Anugrah Ramadhan"
languageCode = "id-ID"
rssLimit    = 20
theme       = "anugrahtheme"

copyright  = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."

[author]
  name  = "Anugrah Ramadhan"
  email = "dialog.anugrah@gmail.com"

[markup.goldmark.renderer]
  unsafe = true

# ===========================
# MENUS
# ===========================
[[menu.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Dukung"
  url    = "https://saweria.co/AnugrahRamadhan"
  weight = 2

[[menu.main]]
  name   = "Kontak"
  url    = "/kontak/"
  weight = 3

[[menu.main]]
  name   = "RSS"
  url    = "/catatan/index.xml"
  weight = 5

# ===========================
# URL & TAXONOMIES
# ===========================
[permalinks]
  posts = "/catatan/:title/"

[taxonomies]
  category = "categories"
  tag      = "tags"
  tagline  = "tagline"
  image    = "image"

# ===============
# MENU LANDING
# ===============
[menu]

  [[menu.landing]]
    name = "üìù Baca catatan terbaru"
    url = "/catatan/"
    weight = 1

# ===============
# MENU TULISAN FOR YOU
# ===============

  [[menu.tulisan]]
  name = "We are all the noseless Voldemort"
  url = "/catatan/we-are-all-the-noseless-voldemort/"

  [[menu.tulisan]]
  name = "Olahraga"
  url = "/catatan/olahraga/"

  [[menu.tulisan]]
  name = "[Resensi Buku] Flip Da Skrip: Kumpulan Catatan Rap Nerd Selama Satu Dekade"
  url = "/catatan/resensi-buku-flip-da-skrip-kumpulan-catatan-rap-nerd-selama-satu-dekade/"

  [[menu.tulisan]]
  name = "Bengkel Siasat"
  url = "/catatan/bengkel-siasat/"

# ===============
# MENU RESENSI
# ===============

  [[menu.review]]
  name = "Anjing lah"
  url = "/catatan/das-kapital/"
  weight = 1