baseURL = "https://anugrahra.space/"
languageCode = "en-us"
title = "Anugrah Ramadhan's Digital Museum ğŸº"
theme = "anugrahtheme"
rssLimit = 20
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[author]
	name = "Anugrah Ramadhan"
	email = "me@example.com"

[permalinks]
  posts = "/catatan/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Dukung"
    url = "https://saweria.com/AnugrahRamadhan"
    weight = 2
  [[menu.main]]
    name = "Kontak"
    url = "/kontak/"
    weight = 3
  [[menu.main]]
    name = "RSS"
    url = "/catatan/index.xml"
    weight = 4

  [[menu.landing]]
    name = "ğŸ“ Catatan"
    url = "/catatan/"
    weight = 1
  [[menu.landing]]
    name = "ğŸ“š Seri Tulisan"
    url = "/seri-tulisan/"
    weight = 2
  [[menu.landing]]
    name = "ğŸ¤– Karya Koding"
    url = "/karya-koding/"
    weight = 3
  [[menu.landing]]
    name = "ğŸ¨ Artwork"
    url = "/artwork/"
    weight = 4
  [[menu.landing]]
    name = "ğŸ™ï¸ Podcast"
    url = "/podcast/"
    weight = 5
